### ISSUE TITLE
Launching with moon rarity feature disabled causes round start exception

### ISSUE THREAD

**Issue by DeathWrench** [Doug-Murphy/LethalCompanyMods#29] opened 2024-02-01 12:19 UTC
With Balanced Items/General Improvements mod: 
![image](https://github.com/Doug-Murphy/LethalCompanyMods/assets/45341450/6393e239-a8c8-4d32-b786-88b7dd174a65)

Without Balanced Items, General Improvements is now working fine: 
![image](https://github.com/Doug-Murphy/LethalCompanyMods/assets/45341450/fbc7746a-ead1-4cbc-ab41-fbf6f204a64a)

**Comment by Doug-Murphy** [comment] 2024-02-01 13:15
With BI. With GI.
![image](https://github.com/Doug-Murphy/LethalCompanyMods/assets/1383347/3a7d39c6-f613-4c41-bdf1-130a39539513)

Without BI. With GI.
![image](https://github.com/Doug-Murphy/LethalCompanyMods/assets/1383347/c1a13f90-ff53-464f-aa42-fe99a7720be1)


I'm not able to reproduce this on my end with these two mods. What other mods do you have installed? I'm also not seeing anything weird in the logs from either mod regarding warnings or errors. Can you attach your log file here?

If you're using r2modman, you can find the log file by pasting this into your Windows Explorer bar: `%appdata%\r2modmanPlus-local\LethalCompany\profiles\<profile-name>\BepInEx` Replace <profile-name> with whatever your profile is named (if you're not sure, then it's pretty much guaranteed to be Default).

**Comment by DeathWrench** [comment] 2024-02-01 13:52
Here is the modpack, I've included the configs in it as well.
https://thunderstore.io/c/lethal-company/p/DeathWrench/BestestModpack/

**Comment by Doug-Murphy** [comment] 2024-02-01 22:12
I was able to find the issue. It turns out it all stems from having the moon rarity feature toggle disabled. The issue is that when you have the feature disabled, the mod "overrides" the item's rarity on the moon to be the vanilla values. But if your game is launched and the round is started with the toggle set to `false`, then the vanilla values are never stored, thus we can't retrieve it to go back to it. :)

I won't have any time tonight to work on a fix, but a solution for now is to toggle the feature on but use vanilla values for the rarities. You may even already have vanilla values specified (I don't have time to confirm that right now). The mod doesn't actually do any overrides out of the box **except for weights**, so you only need to toggle the moon rarities and sell value features off if you have custom overrides for them but don't want them enabled for a particular run.

The fix that I have in mind will take a little bit of time because the issue is due to how I set the vanilla values for items. I tied that syncing with the config file. That's really a dumb approach and I would much rather just set all vanilla values up front before pretty much anything happens. :D I took this approach because it would be more efficient, but the added complexity just isn't worth it. I'll refactor all of this and get the fix out as soon as I can! Thanks for the report. :) Stay tuned for this issue to be closed as it will close at the same time that I release a fix.

**Comment by Doug-Murphy** [comment] 2024-02-02 02:34
@DeathWrench I wound up having a bit of time this evening. The fix was pretty quick. I have a beta release out if you'd like to try it before I officially release 1.5.2. I plan to release it probably tomorrow afternoon ET.

https://github.com/Doug-Murphy/LethalCompanyMods/releases/tag/BI-1.5.2-beta1

For installation instructions, see [this other issue](https://github.com/Doug-Murphy/LethalCompanyMods/issues/2#issuecomment-1874235504). I really should just make a wiki page for this by now.

**Comment by DeathWrench** [comment] 2024-02-02 12:49
Yeah, that fixed it! The Profit Quota thing is from my save being bugged I think.

**Comment by Doug-Murphy** [comment] 2024-02-02 12:50
Reopening. Haven't released yet. But I'll take your closure as confirmation it works.

**Comment by Doug-Murphy** [comment] 2024-02-02 13:52
1.5.2 has been released. Thanks for the bug report!

**Closed** 2024-02-02 13:52 UTC
Labels: bug, mod: Balanced Items
